name: stackoverflow_users
description: Flutter app to display a list of stackoverflow users, their reputation and bookmark favorite users

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  equatable: ^2.0.5
  easy_localization: ^3.0.3
  either_dart: ^1.0.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3
  infinite_scroll_pagination: ^4.0.0
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  bloc_test: ^9.1.5

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
